@startuml
skinparam classAttributeIconSize 0
interface _SwitchCases {
    """
    class contains some methods which switch chars
    """
    .. Constructor ..
    +__init__(line: str):
    """
    Constructor
    **Args:**
        line: исходная строка
    """
    .. Attributes ..
    -__line: str
    .. Methods ..
    +upper() -> str:
    """
    Return copy of the string in upper case
    """
    +lower() -> str:
    """
    Return copy of the string in lower case
    """
    +title() -> str:
}
@enduml
