line = "text4 a b C 1 4 12 fDg\t dgs"
line2 = "t\text4 a b C 1 4 12 fDg\t dgs"
print(line)
print(line.title())
print(line.capitalize())
print(line.casefold())
print(line.lower())
print(line.swapcase())
print(line.upper())
print(line)
print(line.split())
print(line.split(" 1 "))
print(line.partition("1"))
print(line.partition("    1 "))
print(line.partition("    1 "))
print(line.center(100, "$"))
print(line.center(100))
print(line.count("1"))
print(line.find("4"))
print(line.index("4"))
print(line.expandtabs(44))
print(line2.expandtabs(44))
print(line)
print(line2)
print(line.replace("4", "6"))
print(line.replace(" ", ""))
print(", ".join(line.split()))
print(line.rjust(43))
print(line.zfill(55))
